/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.lyncas;

import org.junit.Assert;
import org.junit.jupiter.api.Test;

public class BookshelfTest {

	@Test
	void contextLoads() {
		Assert.assertTrue(true);
	}

}
