/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.lyncas;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.test.context.junit4.SpringRunner;

import net.lyncas.builder.BookshelfBuilder;
import net.lyncas.domain.entity.Bookshelf;
import net.lyncas.usecase.adapters.BookshelfPersistenceAdapter;
import net.lyncas.usecase.services.BookshelfService;

@RunWith(SpringRunner.class)
public class BookshelfServiceTest {

	@Mock
	private BookshelfPersistenceAdapter bookshelfPersistenceAdapter;
	
	@InjectMocks
	private BookshelfService bookshelfService;
	
	@Test
	public void createBookshelf_ok() {
	
		Bookshelf novaEstante = BookshelfBuilder.umaEstante().build();
		
		Bookshelf estanteEsperada = BookshelfBuilder.umaEstante().comId().build();
		
		when(bookshelfPersistenceAdapter.save(novaEstante)).thenReturn(estanteEsperada);
		
		assertEquals(estanteEsperada, novaEstante);
		
	}

}
